### PR TITLE
Protect - fields name can contain a regular expression

### PR DESCRIPTION
**Pull request by andreas4all**
Fields name can contain a regular expression.
No open issue for this.
No depends PR.

### CODE REVIEW

**Comment by daffl** [comment]
Thank you for the pull request! This is a good idea. I am wondering if we could make this a little easier using Lodash [_.omitBy](https://lodash.com/docs/4.17.10#omitBy).

**Comment by andreas4all** [comment]
I tried to refactored with `omitBy`, but I have problem with nested object. Can you help me with that?

**Comment by daffl** [comment]
I was thinking something like:

```js
module.exports = function (...fields) {
  const regExps = fields.filter(isRegExp);
  const fieldNames = fields.filter(field => !isRegExp(field));
  const omitRegex = (value, key) => regExps.some(r => r.test(key));

  return function protect (context) {
    // ...
    const omitted = omit(data, fieldNames);
    // For performance reasons only omit when there are regular expressions
    return regExps.length ? omitBy(omitted, omitRegex) : omitted;
  }
}
```

**Comment by daffl** [comment]
Thanks again for the PR @andreas4all. I am going to close this one for now since this repository will be moved into a monorepo at https://github.com/feathersjs/feathers and I haven't heard back about the changes I proposed.

If you are still interested in getting this in, please reopen the pull request there.

**Pull request closed without merging**
